benchmark_output_path: "${hydra:run.dir}/output.csv"
sysinfo_collector_file: "${hydra:run.dir}/sysinfo.json"

pqos:
  # resets all allocations before applying new ones
  reset_before_apply: true

  classes:
    - id: 1
      description: "real-time workload"
      # Hexademical mask (e.g 0x003 means using the last 2 cache ways)
      l3_mask: "0x00ff"
      l2_mask: "0x00ff"
      mba: 100
      # List of CPU cores assigned to this class
      cores: [9, 11]
    - id: 2
      description: "background worker"
      # Using different cache ways to isolate from class 1
      l3_mask: "0x7f00"
      l2_mask: "0xff00"
      mba: 10
      cores: [0,1,2,3,4,5,6,7,8,10,12,13,14,15]
  
run:
  command: "caterpillar"
  t_core: "9,11"
  stressor: true
  tests_path: "tests"
  metrics: true
  docker: true

caterpillar:
  n_cycles: 7200

megabench:
  caterpillar_cat: "${hydra:run.dir}/caterpillar_cat.csv"
  caterpillar_no_cat: "${hydra:run.dir}/caterpillar_no_cat.csv"
  cyclictest_cat: "${hydra:run.dir}/cyclictest_cat.csv"
  cyclictest_no_cat: "${hydra:run.dir}/cyclictest_no_cat.csv"

cpu_monitor:
  path: "${hydra:run.dir}/cpu_monitor.csv"
  interval: 1.0

irq_monitor:
  path: "${hydra:run.dir}/irq_monitor.csv"
  interval: 1.0

meminfo_monitor:
  path: "${hydra:run.dir}/meminfo_monitor.csv"
  interval: 1.0

softirq_monitor:
  path: "${hydra:run.dir}/softirq_monitor.csv"
  interval: 1.0

cpustat_monitor:
  path: "${hydra:run.dir}/cpustat_monitor.csv"
  interval: 1.0
